### ISSUE TITLE
[BUG] Sever slow when accessing database

### ISSUE THREAD

**Issue by dawnfire05** [gsainfoteam/groups-be#69]
### Description

db에 접근하는 api요청을 보내면 응답속도가 매우 느립니다.

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1.

**Comment by siwonpada** [comment]
어느정도 느린지 객관적인 지표를 알려주시면 더 좋을 것 같습니다.

**Comment by siwonpada** [comment]
어느정도 해결된 것 같아서 일단 닫아두겠습니다.
