### ISSUE TITLE
[BUG] 그룹 삭제 시 500 에러가 뜨는 문제

### ISSUE THREAD

**Issue by GanghyeonSeo** [gsainfoteam/groups-be#77]
### Description

그룹 삭제 시 500 에러가 뜨는 문제가 발생하여 원인을 파악하고 수정해야 합니다.

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1.

**Comment by siwonpada** [comment]
현재 stg에서 했을 때는 크게 문제가 없는 것 같은데 혹시 재현을 하기 위해서 필요한 조건을 알려주실 수 있나요?

**Comment by GanghyeonSeo** [comment]
> 현재 stg에서 했을 때는 크게 문제가 없는 것 같은데 혹시 재현을 하기 위해서 필요한 조건을 알려주실 수 있나요?

앗 이미 해결된 이슈입니다. hotfix로 merge되었습니다. #78 참고하시면 되겠습니다.
